import json

with open("translations.json", "r", encoding="utf-8") as f:
    traducciones = json.load(f)

print(f"Total traducciones antes: {len(traducciones['exercises'])}")

# 1. Correcciones adicionales
correcciones = {
    "cable low fly": "Cruce de poleas bajo",
    "cable standing fly": "Cruce de poleas de pie",
    "cable standing cross-over": "Cruce de poleas de pie",
    "cable crossover": "Cruce de poleas",
    "cable chest fly": "Cruce de poleas al pecho",
    "cable incline fly": "Cruce de poleas inclinado",
    "cable decline fly": "Cruce de poleas declinado",
    "cable high fly": "Cruce de poleas alto",
    "cable middle fly": "Cruce de poleas medio",
    "cable one arm fly": "Cruce de poleas a una mano",
    "cable one arm low fly": "Cruce de poleas bajo a una mano",
    "cable one arm high fly": "Cruce de poleas alto a una mano",
    "cable one arm mid fly": "Cruce de poleas medio a una mano",
    "cable standing one arm chest press": "Press de pecho a una mano en polea",
    "cable seated chest press": "Press de pecho sentado en polea",
    "cable standing chest press": "Press de pecho de pie en polea",
    "cable standing rear delt row": "Remo de deltoides posterior en polea",
    "cable standing twist": "Giros en polea de pie",
    "cable seated twist": "Giros en polea sentado",
    "cable woodchop": "Leñador en polea",
    "cable reverse woodchop": "Leñador inverso en polea",
    "cable kneeling crunch": "Crunch de rodillas en polea",
    "cable standing crunch": "Crunch de pie en polea",
    "cable high pulley overhead tricep extension": "Extensión de tríceps sobre la cabeza en polea alta",
    "cable low pulley overhead tricep extension": "Extensión de tríceps sobre la cabeza en polea baja",
    "cable tricep pushdown": "Extensión de tríceps en polea",
    "cable rope pushdown": "Extensión de tríceps con cuerda en polea",
    "cable bar pushdown": "Extensión de tríceps con barra en polea",
    "cable one arm pushdown": "Extensión de tríceps a una mano en polea",
    "cable one arm reverse pushdown": "Extensión inversa de tríceps a una mano en polea",
    "cable hammer curl": "Curl martillo en polea",
    "cable curl": "Curl en polea",
    "cable one arm curl": "Curl a una mano en polea",
    "cable one arm preacher curl": "Curl predicador a una mano en polea",
    "cable lateral raise": "Elevaciones laterales en polea",
    "cable front raise": "Elevaciones frontales en polea",
    "cable rear delt fly": "Pájaros en polea",
    "cable one arm lateral raise": "Elevaciones laterales a una mano en polea",
    "cable one arm front raise": "Elevaciones frontales a una mano en polea",
    "cable upright row": "Remo al mentón en polea",
    "cable shrug": "Encogimientos en polea",
    "cable pull through": "Pull through en polea",
    "cable hip abduction": "Abducción de cadera en polea",
    "cable hip adduction": "Aducción de cadera en polea",
    "cable kickback": "Patada de glúteo en polea",
    "cable lying tricep extension": "Extensión de tríceps tumbado en polea",
    "cable overhead tricep extension": "Extensión de tríceps sobre la cabeza en polea",
    "cable seated one arm tricep extension": "Extensión de tríceps a una mano sentado en polea",
    "cable seated tricep extension": "Extensión de tríceps sentado en polea",
    "cable standing one arm tricep extension": "Extensión de tríceps a una mano de pie en polea",
    "cable standing tricep extension": "Extensión de tríceps de pie en polea",
    "cable squat": "Sentadilla en polea",
    "cable pull down": "Jalón en polea",
    "cable reverse grip pull down": "Jalón en polea agarre inverso",
    "cable seated row": "Remo sentado en polea",
    "cable one arm seated row": "Remo sentado a una mano en polea",
    "cable standing pullover": "Pullover de pie en polea",
    "cable kneeling pullover": "Pullover de rodillas en polea",
    "cable lying pullover": "Pullover tumbado en polea",
    "cable standing bicep curl": "Curl de bíceps de pie en polea",
    "cable seated bicep curl": "Curl de bíceps sentado en polea",
    "cable preacher curl": "Curl predicador en polea",
    "cable concentration curl": "Curl concentrado en polea",
    "cable incline curl": "Curl inclinado en polea",
    "cable decline curl": "Curl declinado en polea",
    "cable spider curl": "Curl araña en polea",
    "cable reverse curl": "Curl inverso en polea",
    "cable wrist curl": "Curl de muñeca en polea",
    "cable reverse wrist curl": "Curl inverso de muñeca en polea",
    "cable one arm wrist curl": "Curl de muñeca a una mano en polea",
    "cable one arm reverse wrist curl": "Curl inverso de muñeca a una mano en polea",
    "cable standing calf raise": "Elevación de gemelos de pie en polea",
    "cable seated calf raise": "Elevación de gemelos sentado en polea",
    "cable leg extension": "Extensiones de cuádriceps en polea",
    "cable leg curl": "Curl femoral en polea",
    "cable lying leg curl": "Curl femoral tumbado en polea",
    "cable seated leg curl": "Curl femoral sentado en polea",
    "cable standing leg curl": "Curl femoral de pie en polea",
    "cable one arm leg curl": "Curl femoral a una mano en polea",
    "cable lunge": "Zancadas en polea",
    "cable squat row": "Sentadilla con remo en polea",
    "cable deadlift": "Peso muerto en polea",
    "cable romanian deadlift": "Peso muerto rumano en polea",
    "cable stiff leg deadlift": "Peso muerto piernas rígidas en polea",
    "cable sumo deadlift": "Peso muerto sumo en polea",
    "cable good morning": "Buenos días en polea",
    "cable hip thrust": "Hip thrust en polea",
    "cable glute bridge": "Puente de glúteos en polea",
    "cable mountain climber": "Escalador en polea",
    "cable plank": "Plancha en polea",
    "cable side plank": "Plancha lateral en polea",
    "cable crunch": "Crunch en polea",
    "cable reverse crunch": "Crunch inverso en polea",
    "cable leg raise": "Elevación de piernas en polea",
    "cable hanging leg raise": "Elevación de piernas colgado en polea",
    "cable russian twist": "Giros rusos en polea",
    "cable bicycle crunch": "Crunch bicicleta en polea",
    "cable ab wheel rollout": "Rueda abdominal en polea",
    "cable sit-up": "Abdominales en polea",
    "cable v-up": "V-up en polea",
    "cable flutter kicks": "Patadas de aleta en polea",
    "cable woodchop": "Leñador en polea",
    "cable reverse woodchop": "Leñador inverso en polea",
    "cable standing twist": "Giros de pie en polea",
    "cable seated twist": "Giros sentado en polea",
    "cable oblique crunch": "Crunch oblicuo en polea",
    "cable side bend": "Flexión lateral en polea",
    "cable standing side bend": "Flexión lateral de pie en polea",
    "cable seated side bend": "Flexión lateral sentado en polea",
    "cable one arm side bend": "Flexión lateral a una mano en polea",
    "cable pallof press": "Press Pallof en polea",
    "cable anti-rotation press": "Press anti-rotación en polea",
    "cable face pull": "Face pull en polea",
    "cable rear delt row": "Remo de deltoides posterior en polea",
    "cable upright row": "Remo al mentón en polea",
    "cable shrug": "Encogimientos en polea",
    "cable one arm shrug": "Encogimientos a una mano en polea",
    "cable lateral raise": "Elevaciones laterales en polea",
    "cable front raise": "Elevaciones frontales en polea",
    "cable rear delt fly": "Pájaros en polea",
    "cable one arm lateral raise": "Elevaciones laterales a una mano en polea",
    "cable one arm front raise": "Elevaciones frontales a una mano en polea",
    "cable one arm rear delt fly": "Pájaros a una mano en polea",
    "cable shoulder press": "Press de hombros en polea",
    "cable one arm shoulder press": "Press de hombros a una mano en polea",
    "cable arnold press": "Press Arnold en polea",
    "cable high pull": "Jalón alto en polea",
    "cable low pull": "Jalón bajo en polea",
    "cable middle pull": "Jalón medio en polea",
    "cable upright row": "Remo al mentón en polea",
    "cable reverse grip upright row": "Remo al mentón agarre inverso en polea",
    "cable bent over row": "Remo inclinado en polea",
    "cable one arm bent over row": "Remo inclinado a una mano en polea",
    "cable seated row": "Remo sentado en polea",
    "cable one arm seated row": "Remo sentado a una mano en polea",
    "cable standing row": "Remo de pie en polea",
    "cable one arm standing row": "Remo de pie a una mano en polea",
    "cable t-bar row": "Remo en barra T en polea",
    "cable pendlay row": "Remo Pendlay en polea",
    "cable chest supported row": "Remo con apoyo en pecho en polea",
    "cable inverted row": "Remo invertido en polea",
    "cable one arm inverted row": "Remo invertido a una mano en polea",
    "cable pull-up": "Dominadas en polea",
    "cable chin-up": "Dominadas agarre supino en polea",
    "cable assisted pull-up": "Dominadas asistidas en polea",
    "cable assisted chin-up": "Dominadas agarre supino asistidas en polea",
    "cable lat pulldown": "Jalón al pecho en polea",
    "cable one arm lat pulldown": "Jalón al pecho a una mano en polea",
    "cable reverse grip lat pulldown": "Jalón al pecho agarre inverso en polea",
    "cable neutral grip lat pulldown": "Jalón al pecho agarre neutro en polea",
    "cable wide grip lat pulldown": "Jalón al pecho agarre ancho en polea",
    "cable close grip lat pulldown": "Jalón al pecho agarre cerrado en polea",
    "cable straight arm pulldown": "Jalón con brazos extendidos en polea",
    "cable one arm straight arm pulldown": "Jalón con brazos extendidos a una mano en polea",
    "cable pullover": "Pullover en polea",
    "cable one arm pullover": "Pullover a una mano en polea",
    "cable standing pullover": "Pullover de pie en polea",
    "cable kneeling pullover": "Pullover de rodillas en polea",
    "cable lying pullover": "Pullover tumbado en polea",
    "cable seated pullover": "Pullover sentado en polea",
    "cable incline pullover": "Pullover inclinado en polea",
    "cable decline pullover": "Pullover declinado en polea",
    "cable chest press": "Press de pecho en polea",
    "cable one arm chest press": "Press de pecho a una mano en polea",
    "cable seated chest press": "Press de pecho sentado en polea",
    "cable standing chest press": "Press de pecho de pie en polea",
    "cable incline chest press": "Press de pecho inclinado en polea",
    "cable decline chest press": "Press de pecho declinado en polea",
    "cable fly": "Aperturas en polea",
    "cable one arm fly": "Aperturas a una mano en polea",
    "cable chest fly": "Aperturas al pecho en polea",
    "cable incline fly": "Aperturas inclinadas en polea",
    "cable decline fly": "Aperturas declinadas en polea",
    "cable high fly": "Aperturas altas en polea",
    "cable low fly": "Aperturas bajas en polea",
    "cable middle fly": "Aperturas medias en polea",
    "cable crossover": "Cruce de poleas",
    "cable one arm crossover": "Cruce de poleas a una mano",
    "cable standing crossover": "Cruce de poleas de pie",
    "cable seated crossover": "Cruce de poleas sentado",
    "cable incline crossover": "Cruce de poleas inclinado",
    "cable decline crossover": "Cruce de poleas declinado",
    "cable high crossover": "Cruce de poleas alto",
    "cable low crossover": "Cruce de poleas bajo",
    "cable middle crossover": "Cruce de poleas medio",
    "cable chest dip": "Fondos de pecho en polea",
    "cable tricep dip": "Fondos de tríceps en polea",
    "cable assisted dip": "Fondos asistidos en polea",
    "cable push-up": "Flexiones en polea",
    "cable one arm push-up": "Flexiones a una mano en polea",
    "cable wide grip push-up": "Flexiones agarre ancho en polea",
    "cable close grip push-up": "Flexiones agarre cerrado en polea",
    "cable incline push-up": "Flexiones inclinadas en polea",
    "cable decline push-up": "Flexiones declinadas en polea",
    "cable diamond push-up": "Flexiones diamante en polea",
    "cable archer push-up": "Flexiones de arquero en polea",
    "cable plank": "Plancha en polea",
    "cable side plank": "Plancha lateral en polea",
    "cable crunch": "Crunch en polea",
    "cable reverse crunch": "Crunch inverso en polea",
    "cable leg raise": "Elevación de piernas en polea",
    "cable hanging leg raise": "Elevación de piernas colgado en polea",
    "cable russian twist": "Giros rusos en polea",
    "cable bicycle crunch": "Crunch bicicleta en polea",
    "cable mountain climber": "Escalador en polea",
    "cable ab wheel rollout": "Rueda abdominal en polea",
    "cable sit-up": "Abdominales en polea",
    "cable v-up": "V-up en polea",
    "cable flutter kicks": "Patadas de aleta en polea",
    "cable woodchop": "Leñador en polea",
    "cable reverse woodchop": "Leñador inverso en polea",
    "cable standing twist": "Giros de pie en polea",
    "cable seated twist": "Giros sentado en polea",
    "cable oblique crunch": "Crunch oblicuo en polea",
    "cable side bend": "Flexión lateral en polea",
    "cable standing side bend": "Flexión lateral de pie en polea",
    "cable seated side bend": "Flexión lateral sentado en polea",
    "cable one arm side bend": "Flexión lateral a una mano en polea",
    "cable pallof press": "Press Pallof en polea",
    "cable anti-rotation press": "Press anti-rotación en polea",
}

corregidas = 0
for clave, traduccion_correcta in correcciones.items():
    if clave in traducciones["exercises"]:
        traducciones["exercises"][clave] = traduccion_correcta
        corregidas += 1

print(f"✅ {corregidas} traducciones corregidas")

# 2. Capitalizar la primera letra de TODAS las traducciones
capitalizadas = 0
for clave, valor in traducciones["exercises"].items():
    if valor and valor[0].islower():
        traducciones["exercises"][clave] = valor[0].upper() + valor[1:]
        capitalizadas += 1

print(f"✅ {capitalizadas} traducciones capitalizadas")

# 3. Capitalizar también equipos y músculos
for clave, valor in traducciones.get("equipment", {}).items():
    if valor and valor[0].islower():
        traducciones["equipment"][clave] = valor[0].upper() + valor[1:]

for clave, valor in traducciones.get("muscles", {}).items():
    if valor and valor[0].islower():
        traducciones["muscles"][clave] = valor[0].upper() + valor[1:]

with open("translations.json", "w", encoding="utf-8") as f:
    json.dump(traducciones, f, indent=2, ensure_ascii=False)

print(f"✅ Guardado con {len(traducciones['exercises'])} traducciones")