import requests
import json

print("Descargando ejercicios...")
url = "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/data/exercises.json"
response = requests.get(url)
exercises = response.json()
print(f"Descargados {len(exercises)} ejercicios")

TRADUCCIONES = {
    "barbell bench press": "Press de banca con barra",
    "barbell decline bench press": "Press de banca declinado con barra",
    "barbell incline bench press": "Press de banca inclinado con barra",
    "barbell wide-grip bench press": "Press de banca agarre ancho con barra",
    "barbell close-grip bench press": "Press de banca agarre cerrado con barra",
    "barbell reverse-grip bench press": "Press de banca agarre inverso con barra",
    "barbell guillotine bench press": "Press de banca guillotina con barra",
    "dumbbell bench press": "Press de banca con mancuernas",
    "dumbbell incline bench press": "Press de banca inclinado con mancuernas",
    "dumbbell decline bench press": "Press de banca declinado con mancuernas",
    "dumbbell fly": "Aperturas con mancuernas",
    "dumbbell incline fly": "Aperturas inclinadas con mancuernas",
    "dumbbell decline fly": "Aperturas declinadas con mancuernas",
    "smith machine bench press": "Press de banca en maquina Smith",
    "smith machine incline bench press": "Press de banca inclinado en maquina Smith",
    "smith machine decline bench press": "Press de banca declinado en maquina Smith",
    "machine chest press": "Press de pecho en maquina",
    "machine incline chest press": "Press de pecho inclinado en maquina",
    "machine decline chest press": "Press de pecho declinado en maquina",
    "push-up": "Flexiones",
    "incline push-up": "Flexiones inclinadas",
    "decline push-up": "Flexiones declinadas",
    "wide-grip push-up": "Flexiones agarre ancho",
    "close-grip push-up": "Flexiones agarre cerrado",
    "diamond push-up": "Flexiones diamante",
    "archer push-up": "Flexiones de arquero",
    "clap push-up": "Flexiones con aplauso",
    "explosive push-up": "Flexiones explosivas",
    "plyo push-up": "Flexiones pliometricas",
    "one arm push-up": "Flexiones a una mano",
    "chest dip": "Fondos en paralelas",
    "wide-grip chest dip": "Fondos en paralelas agarre ancho",
    "assisted chest dip": "Fondos en paralelas asistidos",
    "cable crossover": "Cruce de poleas",
    "cable chest fly": "Cruce de poleas al pecho",
    "cable incline fly": "Cruce de poleas inclinado",
    "cable decline fly": "Cruce de poleas declinado",
    "cable high fly": "Cruce de poleas alto",
    "cable low fly": "Cruce de poleas bajo",
    "cable middle fly": "Cruce de poleas medio",
    "cable one arm fly": "Cruce de poleas a una mano",
    "cable upper chest crossover": "Cruce de poleas pecho superior",
    "cable lower chest crossover": "Cruce de poleas pecho inferior",
    "cable middle chest crossover": "Cruce de poleas pecho medio",
    "cable standing crossover": "Cruce de poleas de pie",
    "cable seated crossover": "Cruce de poleas sentado",
    "pec deck fly": "Aperturas en maquina pec-deck",
    "barbell pullover": "Pullover con barra",
    "dumbbell pullover": "Pullover con mancuerna",
    "barbell bent arm pullover": "Pullover con barra",
    "barbell straight arm pullover": "Pullover con brazos extendidos",
    "jersey barbell": "Pullover con barra",
    "jersey barbell decline": "Pullover con barra en banco declinado",
    "sweater barbell": "Pullover con barra",
    "sweater barbell decline": "Pullover con barra en banco declinado",
    "assisted seated pectoralis major stretch with stability ball": "Estiramiento de pecho asistido con balon",
    "standing chest stretch": "Estiramiento de pecho de pie",
    "svend press": "Press Svend",
    "landmine press": "Press landmine",
    "cable chest press": "Press de pecho en polea",
    "cable one arm chest press": "Press de pecho a una mano en polea",
    "cable seated chest press": "Press de pecho sentado en polea",
    "cable standing chest press": "Press de pecho de pie en polea",
    "cable incline chest press": "Press de pecho inclinado en polea",
    "cable decline chest press": "Press de pecho declinado en polea",
    "cable decline press": "Press declinado en polea",
    "cable one arm decline press": "Press declinado a una mano en polea",
    "cable incline press": "Press inclinado en polea",
    "cable one arm incline press": "Press inclinado a una mano en polea",
    "pull-up": "Dominadas",
    "wide-grip pull-up": "Dominadas agarre ancho",
    "close-grip pull-up": "Dominadas agarre cerrado",
    "neutral-grip pull-up": "Dominadas agarre neutro",
    "assisted pull-up": "Dominadas asistidas",
    "chin-up": "Dominadas agarre supino",
    "assisted chin-up": "Dominadas agarre supino asistidas",
    "lat pulldown": "Jalon al pecho",
    "wide-grip lat pulldown": "Jalon al pecho agarre ancho",
    "close-grip lat pulldown": "Jalon al pecho agarre cerrado",
    "neutral-grip lat pulldown": "Jalon al pecho agarre neutro",
    "reverse-grip lat pulldown": "Jalon al pecho agarre inverso",
    "barbell bent over row": "Remo con barra",
    "barbell pendlay row": "Remo Pendlay con barra",
    "barbell t-bar row": "Remo en barra T",
    "dumbbell row": "Remo con mancuerna",
    "one arm dumbbell row": "Remo con mancuerna a una mano",
    "dumbbell bent over row": "Remo con mancuerna inclinado",
    "seated cable row": "Remo en polea baja",
    "one arm cable row": "Remo en polea a una mano",
    "machine row": "Remo en maquina",
    "chest supported row": "Remo con apoyo en pecho",
    "deadlift": "Peso muerto",
    "barbell deadlift": "Peso muerto con barra",
    "romanian deadlift": "Peso muerto rumano",
    "sumo deadlift": "Peso muerto sumo",
    "stiff leg deadlift": "Peso muerto piernas rigidas",
    "rack pull": "Rack pull",
    "face pull": "Face pull",
    "barbell shrug": "Encogimientos con barra",
    "dumbbell shrug": "Encogimientos con mancuernas",
    "trap bar shrug": "Encogimientos con barra trapecio",
    "hyperextension": "Hiperextensiones lumbares",
    "back extension": "Extensiones de espalda",
    "good morning": "Buenos dias",
    "barbell squat": "Sentadilla con barra",
    "barbell high bar squat": "Sentadilla con barra alta",
    "barbell low bar squat": "Sentadilla con barra baja",
    "front squat": "Sentadilla frontal",
    "goblet squat": "Sentadilla goblet",
    "hack squat": "Sentadilla hack",
    "leg press": "Prensa de piernas",
    "sled 45 degree leg press": "Prensa de piernas a 45 grados",
    "lever leg press": "Prensa de piernas horizontal",
    "barbell lunge": "Zancadas con barra",
    "dumbbell lunge": "Zancadas con mancuernas",
    "walking lunge": "Zancadas caminando",
    "reverse lunge": "Zancada hacia atras",
    "lateral lunge": "Zancada lateral",
    "bulgarian split squat": "Sentadilla bulgara",
    "step-up": "Step-up",
    "leg extension": "Extensiones de cuadriceps",
    "lying leg curl": "Curl femoral tumbado",
    "seated leg curl": "Curl femoral sentado",
    "standing leg curl": "Curl femoral de pie",
    "barbell hip thrust": "Hip thrust con barra",
    "glute bridge": "Puente de gluteos",
    "cable kickback": "Patada de gluteo en polea",
    "hip abduction": "Abduccion de cadera",
    "hip adduction": "Aduccion de cadera",
    "calf raise": "Elevacion de gemelos",
    "barbell calf raise": "Elevacion de gemelos con barra",
    "seated calf raise": "Elevacion de gemelos sentado",
    "leg press calf raise": "Elevacion de gemelos en prensa",
    "donkey calf raise": "Elevacion de gemelos tipo burro",
    "single leg calf raise": "Elevacion de gemelos a una pierna",
    "barbell shoulder press": "Press militar con barra",
    "dumbbell shoulder press": "Press militar con mancuernas",
    "arnold press": "Press Arnold",
    "machine shoulder press": "Press de hombros en maquina",
    "smith machine shoulder press": "Press de hombros en maquina Smith",
    "lateral raise": "Elevaciones laterales",
    "dumbbell lateral raise": "Elevaciones laterales con mancuernas",
    "cable lateral raise": "Elevaciones laterales en polea",
    "machine lateral raise": "Elevaciones laterales en maquina",
    "front raise": "Elevaciones frontales",
    "dumbbell front raise": "Elevaciones frontales con mancuernas",
    "barbell front raise": "Elevaciones frontales con barra",
    "rear delt fly": "Pajaros (deltoides posterior)",
    "dumbbell rear delt fly": "Pajaros con mancuernas",
    "reverse pec deck fly": "Pajaros en maquina inversa",
    "cable rear delt fly": "Pajaros en polea",
    "upright row": "Remo al menton",
    "barbell upright row": "Remo al menton con barra",
    "dumbbell upright row": "Remo al menton con mancuernas",
    "barbell curl": "Curl de biceps con barra",
    "dumbbell curl": "Curl de biceps con mancuernas",
    "ez bar curl": "Curl con barra Z",
    "hammer curl": "Curl martillo",
    "dumbbell hammer curl": "Curl martillo con mancuernas",
    "cable hammer curl": "Curl martillo en polea",
    "preacher curl": "Curl predicador",
    "barbell preacher curl": "Curl predicador con barra",
    "dumbbell preacher curl": "Curl predicador con mancuernas",
    "concentration curl": "Curl concentrado",
    "cable curl": "Curl en polea",
    "incline dumbbell curl": "Curl inclinado con mancuernas",
    "spider curl": "Curl arana",
    "reverse barbell curl": "Curl inverso con barra",
    "reverse dumbbell curl": "Curl inverso con mancuernas",
    "wrist curl": "Curl de muneca",
    "reverse wrist curl": "Curl inverso de muneca",
    "tricep pushdown": "Extension de triceps en polea",
    "rope pushdown": "Extension de triceps con cuerda",
    "bar pushdown": "Extension de triceps con barra",
    "overhead tricep extension": "Extension de triceps sobre la cabeza",
    "dumbbell overhead tricep extension": "Extension de triceps sobre la cabeza con mancuerna",
    "cable overhead tricep extension": "Extension de triceps sobre la cabeza en polea",
    "skull crusher": "Rompecranos",
    "lying tricep extension": "Extension de triceps tumbado",
    "tricep dip": "Fondos de triceps",
    "close-grip bench press": "Press de banca agarre cerrado",
    "plank": "Plancha",
    "side plank": "Plancha lateral",
    "crunch": "Crunch abdominal",
    "decline crunch": "Crunch declinado",
    "cable crunch": "Crunch en polea",
    "reverse crunch": "Crunch inverso",
    "leg raise": "Elevacion de piernas",
    "hanging leg raise": "Elevacion de piernas colgado",
    "lying leg raise": "Elevacion de piernas tumbado",
    "russian twist": "Giros rusos",
    "bicycle crunch": "Crunch bicicleta",
    "mountain climber": "Escalador",
    "ab wheel rollout": "Rueda abdominal",
    "sit-up": "Abdominales",
    "3/4 sit-up": "Abdominales 3/4",
    "v-up": "V-up",
    "flutter kicks": "Patadas de aleta",
    "woodchop": "Lenador",
    "cable woodchop": "Lenador en polea",
    "burpee": "Burpee",
    "running": "Correr",
    "cycling": "Ciclismo",
    "jump rope": "Saltar a la cuerda",
    "jumping jacks": "Saltos de tijera",
    "rowing": "Remo",
    "elliptical trainer": "Eliptica",
    "stair climber": "Escaladora",
    "treadmill": "Cinta de correr",
    "stationary bike": "Bicicleta estatica",
    "box jump": "Salto al cajon",
    "battle ropes": "Cuerdas de batalla",
    "kettlebell swing": "Swing con pesa rusa",
    "thruster": "Thruster",
    "clean and jerk": "Cargada y jerk",
    "snatch": "Arranque",
    "power clean": "Cargada de potencia",
    "high knees": "Rodillas al pecho",
    "butt kicks": "Talones al gluteo",
    "squat jump": "Sentadilla con salto",
    "lateral jump": "Salto lateral",
    "clock push-up": "Flexiones reloj",
}

EQUIPOS = {
    "barbell": "Barra",
    "dumbbell": "Mancuernas",
    "cable": "Polea",
    "machine": "Maquina",
    "body weight": "Peso corporal",
    "kettlebell": "Pesa rusa",
    "band": "Banda elastica",
    "leverage machine": "Maquina de palanca",
    "assisted": "Asistido",
    "smith machine": "Maquina Smith",
    "ez barbell": "Barra Z",
    "trap bar": "Barra trapecio",
    "olympic barbell": "Barra olimpica",
    "bosu ball": "Bosu",
    "medicine ball": "Balon medicinal",
    "stability ball": "Balon de estabilidad",
    "roller": "Rodillo",
    "wheel roller": "Rueda abdominal",
    "rope": "Cuerda",
    "sled machine": "Maquina de trineo",
    "hammer machine": "Maquina Hammer",
    "barbell pad": "Almohadilla para barra",
    "tire": "Neumatico",
    "hammer": "Martillo",
    "upper body ergometer": "Ergometro de tren superior",
    "skierg machine": "Maquina SkiErg",
    "weighted": "Lastrado",
    "resistance band": "Banda de resistencia",
    "suspension": "Suspension",
}

MUSCULOS = {
    "chest": "Pecho",
    "back": "Espalda",
    "shoulders": "Hombros",
    "upper arms": "Brazos",
    "upper legs": "Piernas",
    "lower legs": "Pantorrillas",
    "waist": "Core",
    "cardio": "Cardio",
    "neck": "Cuello",
    "lower arms": "Antebrazos",
}

traducciones = {
    "exercises": dict(TRADUCCIONES),
    "muscles": MUSCULOS,
    "equipment": EQUIPOS
}

sin_traducir = 0
for ex in exercises:
    nombre = ex['name'].lower()
    if nombre not in traducciones["exercises"]:
        traducciones["exercises"][nombre] = ex['name']
        sin_traducir += 1

print(f"Traducciones manuales: {len(TRADUCCIONES)}")
print(f"Sin traducir (en ingles): {sin_traducir}")
print(f"Total: {len(traducciones['exercises'])}")

with open("translations.json", "w", encoding="utf-8") as f:
    json.dump(traducciones, f, indent=2, ensure_ascii=False)

print("translations.json generado correctamente")